/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-07-01 19:38:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"book_store_stile.css\">\r\n");
      out.write("\t\t<title>BookStore</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"cabecalho\">\r\n");
      out.write("\t\t\t\t<h1>Bem vindo as Compras</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t\t<div class=\"meu-carrinho\">\r\n");
      out.write("\t\t\t\t<div class=\"carrinho\">\t\r\n");
      out.write("\t\t\t\t\t<label id=\"meu-carrinho\">Meu Carrinho</label></br>\r\n");
      out.write("\t\t\t\t\t<label class=\"lbl-itens\">Itens: </label></br>\r\n");
      out.write("\t\t\t\t\t<label class=\"lbl-total\">Total: </label></br>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn\">Finalizar Compras</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table id=\"tbl-books\">\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <th>Titulo</th>\r\n");
      out.write("\t\t\t    <th>Autor</th> \r\n");
      out.write("\t\t\t    <th>Preço (R$)</th>\r\n");
      out.write("\t\t\t    <th>Quantidade de Estoque</th>\r\n");
      out.write("\t\t\t    <th>Comprar</th>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td class=\"nome-livro\">The Pragmatic Programmer: From Journeyman to Master</td>\r\n");
      out.write("\t\t\t    <td class=\"nome-autor\">Andrew Hunt & Dave Thomas</td> \r\n");
      out.write("\t\t\t    <td class=\"preco\">40,00</td>\r\n");
      out.write("\t\t\t    <td class=\"estoque\">12</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\" >Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>The Mythical Man-Month: Essays on Software Engineering</td>\r\n");
      out.write("\t\t\t    <td>Frederick P. Brooks</td> \r\n");
      out.write("\t\t\t    <td>80,00</td>\r\n");
      out.write("\t\t\t    <td>1</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Expressões Regulares - Uma Abordagem Divertida</td>\r\n");
      out.write("\t\t\t    <td>Aurelio Marinho Jargas</td> \r\n");
      out.write("\t\t\t    <td>20,00</td>\r\n");
      out.write("\t\t\t    <td>13</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Domain Driven Design: Tackling Complexity in the Heart of Software</td>\r\n");
      out.write("\t\t\t    <td>Eric Evans</td> \r\n");
      out.write("\t\t\t    <td>120,00</td>\r\n");
      out.write("\t\t\t    <td>42</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Patterns of Enterprise Application Architecture</td>\r\n");
      out.write("\t\t\t    <td>Martin FowIer</td> \r\n");
      out.write("\t\t\t    <td>32,00</td>\r\n");
      out.write("\t\t\t    <td>42</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Epigrams in Programming</td>\r\n");
      out.write("\t\t\t    <td>Alan Perils</td> \r\n");
      out.write("\t\t\t    <td>31,00</td>\r\n");
      out.write("\t\t\t    <td>0</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Implementing Domain-Driven Design</td>\r\n");
      out.write("\t\t\t    <td>Vaughn Vernon</td> \r\n");
      out.write("\t\t\t    <td>31,00</td>\r\n");
      out.write("\t\t\t    <td>42</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td>Dive Into HTML5</td>\r\n");
      out.write("\t\t\t    <td>Mark Pilgrim</td> \r\n");
      out.write("\t\t\t    <td>22,00</td>\r\n");
      out.write("\t\t\t    <td>42</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td>Scalable Internet Architectures</td>\r\n");
      out.write("\t\t\t    <td>Theo Schlossnagle</td> \r\n");
      out.write("\t\t\t    <td>18,00</td>\r\n");
      out.write("\t\t\t    <td>4</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td>Refactoring: Improving the Design of Existing Code</td>\r\n");
      out.write("\t\t\t    <td>Martin Fowler</td> \r\n");
      out.write("\t\t\t    <td>33,00</td>\r\n");
      out.write("\t\t\t    <td>2</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td>Treinamento Em C</td>\r\n");
      out.write("\t\t\t    <td>Victorine Viviane Mizrahi</td> \r\n");
      out.write("\t\t\t    <td>42,00</td>\r\n");
      out.write("\t\t\t    <td>6</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td>Algoritmos: Teoria e Prática</td>\r\n");
      out.write("\t\t\t    <td>Thomas H. Cormen</td> \r\n");
      out.write("\t\t\t    <td>4,60</td>\r\n");
      out.write("\t\t\t    <td>1</td>\r\n");
      out.write("\t\t\t    <td><button class=\"btn\" id=\"btn-comprar\">Comprar</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
